/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_github_jbharter_FasterFFT */

#ifndef _Included_com_github_jbharter_FasterFFT
#define _Included_com_github_jbharter_FasterFFT
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_github_jbharter_FasterFFT
 * Method:    sendMeAnInt
 * Signature: ([C)I
 */
JNIEXPORT jint JNICALL Java_com_github_jbharter_FasterFFT_sendMeAnInt
  (JNIEnv *, jobject, jcharArray);

#ifdef __cplusplus
}
#endif
#endif
